name: Test Server

on:
  pull_request:
    branches:
      - master
    paths:
      - server/**
      - .github/workflows/server_test.yml

jobs:
  build-amd64:
    name: Build amd64
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/amd64

  build-arm64:
    name: Build arm64
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          platforms: linux/arm64

  server-tests:
    name: Server tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "server/go.mod"
          cache: true

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: >
            libgstreamer1.0-dev
            libgstreamer-plugins-base1.0-dev
            libgtk-3-dev
            libx11-dev
            libxrandr-dev
            libxtst-dev
            libxfixes-dev
            libxcvt-dev
            pkg-config
          version: ${{ runner.os }}-ubuntu-24.04

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgtk-3-dev \
            libx11-dev \
            libxrandr-dev \
            libxtst-dev \
            libxfixes-dev \
            libxcvt-dev \
            pkg-config

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Run tests
        working-directory: server
        run: go test ./... -v
